
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtrace_cntrl_32.h"

/*
* The configuration table for devices
*/

XTrace_cntrl_32_Config XTrace_cntrl_32_ConfigTable[XPAR_XTRACE_CNTRL_32_NUM_INSTANCES] =
{
	{
		XPAR_TRACE_ANALYZER_PMODB_TRACE_CNTRL_32_0_DEVICE_ID,
		XPAR_TRACE_ANALYZER_PMODB_TRACE_CNTRL_32_0_S_AXI_TRACE_CNTRL_BASEADDR
	}
};


