# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.srcs/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0.xci
# IP: The module: 'video_out_pynq_z2_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.srcs/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0.xci
# IP: The module: 'video_out_pynq_z2_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PXL/EOS_PXL_2025/Pynq-Z2-Video/hw_proj.gen/sources_1/bd/video_out_pynq_z2/ip/video_out_pynq_z2_v_tpg_0_0/video_out_pynq_z2_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_out_pynq_z2_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
