
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcolor_convert.h"

/*
* The configuration table for devices
*/

XColor_convert_Config XColor_convert_ConfigTable[XPAR_XCOLOR_CONVERT_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_HDMI_IN_COLOR_CONVERT_DEVICE_ID,
		XPAR_VIDEO_HDMI_IN_COLOR_CONVERT_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_VIDEO_HDMI_OUT_COLOR_CONVERT_DEVICE_ID,
		XPAR_VIDEO_HDMI_OUT_COLOR_CONVERT_S_AXI_CONTROL_BASEADDR
	}
};


