# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1.xci
# IP: The module: 'base_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.gen/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.gen/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1.xci
# IP: The module: 'base_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.gen/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/XilinxDev/PBEAI3/HDMI_test_base1/HDMI_test2/HDMI_test2.gen/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
