
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpixel_unpack.h"

/*
* The configuration table for devices
*/

XPixel_unpack_Config XPixel_unpack_ConfigTable[XPAR_XPIXEL_UNPACK_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_HDMI_OUT_PIXEL_UNPACK_DEVICE_ID,
		XPAR_VIDEO_HDMI_OUT_PIXEL_UNPACK_S_AXI_CONTROL_BASEADDR
	}
};


