
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_SYSTEM_INTERRUPTS_DEVICE_ID,
		XPAR_SYSTEM_INTERRUPTS_BASEADDR,
		XPAR_SYSTEM_INTERRUPTS_KIND_OF_INTR,
		XPAR_SYSTEM_INTERRUPTS_HAS_FAST,
		XPAR_SYSTEM_INTERRUPTS_IVAR_RESET_VALUE,
		XPAR_SYSTEM_INTERRUPTS_NUM_INTR_INPUTS,
		XPAR_SYSTEM_INTERRUPTS_ADDR_WIDTH,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_SYSTEM_INTERRUPTS_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			}
		},
		XPAR_SYSTEM_INTERRUPTS_NUM_SW_INTR
	}
};

