#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Script generated by Vivado on Tue Dec 17 14:54:17 +0100 2024
# SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_17 -libname processing_system7_vip_v1_0_19 -libname xil_defaultlib -libname generic_baseblocks_v2_1_2 -libname axi_register_slice_v2_1_31 -libname fifo_generator_v13_2_10 -libname axi_data_fifo_v2_1_30 -libname axi_crossbar_v2_1_32 -libname lib_cdc_v1_0_3 -libname proc_sys_reset_v5_0_15 -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_1_14 -libname v_vid_in_axi4s_v4_0_11 -libname v_axi4s_vid_out_v4_0_18 -libname v_tc_v6_2_8 -libname xbip_utils_v3_0_13 -libname axi_utils_v2_0_9 -libname xbip_pipe_v3_0_9 -libname xbip_dsp48_wrapper_v3_0_6 -libname xbip_dsp48_addsub_v3_0_9 -libname xbip_bram18k_v3_0_9 -libname mult_gen_v12_0_21 -libname floating_point_v7_0_23 -libname xbip_dsp48_mult_v3_0_9 -libname xbip_dsp48_multadd_v3_0_9 -libname div_gen_v5_1_22 -libname v_tpg_v8_2_5 -libname lib_pkg_v1_0_4 -libname lib_fifo_v1_0_19 -libname blk_mem_gen_v8_4_8 -libname lib_bmg_v1_0_17 -libname lib_srl_fifo_v1_0_4 -libname axi_datamover_v5_1_33 -libname axi_vdma_v6_3_19 -libname axi_protocol_converter_v2_1_31 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_17 processing_system7_vip_v1_0_19 xil_defaultlib generic_baseblocks_v2_1_2 axi_register_slice_v2_1_31 fifo_generator_v13_2_10 axi_data_fifo_v2_1_30 axi_crossbar_v2_1_32 lib_cdc_v1_0_3 proc_sys_reset_v5_0_15 axi_lite_ipif_v3_0_4 v_tc_v6_1_14 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_18 v_tc_v6_2_8 xbip_utils_v3_0_13 axi_utils_v2_0_9 xbip_pipe_v3_0_9 xbip_dsp48_wrapper_v3_0_6 xbip_dsp48_addsub_v3_0_9 xbip_bram18k_v3_0_9 mult_gen_v12_0_21 floating_point_v7_0_23 xbip_dsp48_mult_v3_0_9 xbip_dsp48_multadd_v3_0_9 div_gen_v5_1_22 v_tpg_v8_2_5 lib_pkg_v1_0_4 lib_fifo_v1_0_19 blk_mem_gen_v8_4_8 lib_bmg_v1_0_17 lib_srl_fifo_v1_0_4 axi_datamover_v5_1_33 axi_vdma_v6_3_19 axi_protocol_converter_v2_1_31)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2024.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_17 $xmvlog_opts -sv +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_19 $xmvlog_opts -sv +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_processing_system7_0_1/sim/design_1_processing_system7_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_2 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_31 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/1443/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_10 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/1443/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_10 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/1443/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_30 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_32 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/ClockGen.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsync.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsyncReset.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/DVI_Constants.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/OutputSERDES.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/TMDS_Encoder.vhd" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/d57c/src/rgb2dvi.vhd" \
  "../../../bd/design_1/ip/design_1_rgb2dvi_0_1/sim/design_1_rgb2dvi_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_3 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_15 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_100M_1/sim/design_1_rst_ps7_0_100M_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_14 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/fd54/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_11 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_18 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/52cd/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_axi4s_vid_out_0_1/sim/design_1_v_axi4s_vid_out_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_8 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/5959/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_v_tc_0_1/sim/design_1_v_tc_0_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_am_addmul_16ns_1s_16ns_17_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_CTRL_s_axi.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_entry_proc.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w1_d4_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w8_d2_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w8_d3_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w12_d2_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w13_d2_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w16_d2_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w16_d3_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w16_d4_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_fifo_w24_d16_S.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_flow_control_loop_pipe_sequential_init.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_5ns_16ns_17_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_6s_15ns_16_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_7ns_13ns_15_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_7s_16s_16_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_8ns_15ns_16_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_8ns_8s_16s_16_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mac_muladd_16s_16s_16ns_16_4_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mul_11ns_13ns_23_1_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_mul_20s_9ns_28_1_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_MultiPixStream2AXIvideo.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_reg_ap_uint_10_s.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_reg_int_s.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_reg_unsigned_short_s.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_regslice_both.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_sparsemux_7_2_8_1_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_sparsemux_7_2_8_1_1_x.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_sparsemux_7_2_9_1_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_sparsemux_7_2_9_1_1_x.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_sparsemux_7_16_8_1_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_start_for_MultiPixStream2AXIvideo_U0.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_start_for_tpgForeground_U0.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_blkYuv_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_bluYuv_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarArray_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_b_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_g_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_r_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_u_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_v_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_y_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_u_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_v_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_y_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_grnYuv_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_redYuv_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_b_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_g_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_r_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_u_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_v_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_y_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgCheckerBoardArray_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_0_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_1_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_2_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgTartanBarArray_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_whiYuv_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgForeground.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgForeground_Pipeline_VITIS_LOOP_774_2.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_urem_11ns_3ns_2_15_1.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_v_tpgHlsDataFlow.vhd" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/vhdl/design_1_v_tpg_0_1_v_tpg.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_am_addmul_16ns_1s_16ns_17_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_CTRL_s_axi.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_entry_proc.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w1_d4_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w8_d2_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w8_d3_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w12_d2_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w13_d2_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w16_d2_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w16_d3_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w16_d4_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_fifo_w24_d16_S.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_flow_control_loop_pipe_sequential_init.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_hls_deadlock_detection_unit.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_hls_deadlock_idx0_monitor.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_5ns_16ns_17_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_6s_15ns_16_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_7ns_13ns_15_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_7s_16s_16_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_8ns_15ns_16_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_8ns_8s_16s_16_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mac_muladd_16s_16s_16ns_16_4_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mul_11ns_13ns_23_1_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_mul_20s_9ns_28_1_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_MultiPixStream2AXIvideo.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_reg_ap_uint_10_s.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_reg_int_s.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_reg_unsigned_short_s.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_regslice_both.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_sparsemux_7_2_8_1_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_sparsemux_7_2_8_1_1_x.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_sparsemux_7_2_9_1_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_sparsemux_7_2_9_1_1_x.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_sparsemux_7_16_8_1_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_start_for_MultiPixStream2AXIvideo_U0.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_start_for_tpgForeground_U0.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_blkYuv_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_bluYuv_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarArray_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_b_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_g_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelRgb_CEA_r_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_u_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_v_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_601_y_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_u_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_v_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_DPtpgBarSelYuv_709_y_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_grnYuv_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_redYuv_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_b_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_g_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelRgb_r_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_u_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_v_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgBarSelYuv_y_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgCheckerBoardArray_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_0_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_1_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_9bit_2_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgSinTableArray_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_tpgTartanBarArray_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgBackground_Pipeline_VITIS_LOOP_565_2_whiYuv_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgForeground.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgForeground_Pipeline_VITIS_LOOP_774_2.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_urem_11ns_3ns_2_15_1.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_v_tpgHlsDataFlow.v" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog/design_1_v_tpg_0_1_v_tpg.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_13 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_6 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_addsub_v3_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_bram18k_v3_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_21 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_0_23 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_mult_v3_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_multadd_v3_0_9 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work div_gen_v5_1_22 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_tpg_v8_2_5 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/v_tpg_v8_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_tpg_0_1/sim/design_1_v_tpg_0_1.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_4 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_19 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_8 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/09bd/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_bmg_v1_0_17 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3f29/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_4 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_33 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vdma_v6_3_19 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_vdma_v6_3_19 $xmvhdl_opts \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_vdma_0_1/sim/design_1_axi_vdma_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_3/sim/design_1_xbar_3.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_31 $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/b28c/hdl" +incdir+"../../../bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/3242" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ipshared/a4a8/hdl" +incdir+"../../../../hdmi_test.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_1/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_auto_pc_0_3/sim/design_1_auto_pc_0.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_1_3/sim/design_1_auto_pc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
