
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpixel_pack.h"

/*
* The configuration table for devices
*/

XPixel_pack_Config XPixel_pack_ConfigTable[XPAR_XPIXEL_PACK_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_HDMI_IN_PIXEL_PACK_DEVICE_ID,
		XPAR_VIDEO_HDMI_IN_PIXEL_PACK_S_AXI_CONTROL_BASEADDR
	}
};


